### ISSUE TITLE
jQuery Parser: Cannot call method 'value' of null

### ISSUE THREAD

**Issue by ogonkov** [sergeche/jsdt-docs#3]
В чем может быть проблема?

API грузится с http://api.jquery.com/api/

```
$ node main.js 
Loading API

/Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:118
            var type = getType(processType(n.attr('type').value()));
                                                 ^
TypeError: Cannot call method 'value' of null
    at /Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:118:50
    at Array.map (native)
    at Object.JSDocEntry (/Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:116:42)
    at /Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:381:17
    at Array.forEach (native)
    at /Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:380:15
    at Array.forEach (native)
    at Request._callback (/Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/main.js:375:74)
    at Request.callback (/Users/user/Downloads/sergeche-jsdt-docs-8723d58/jquery-parser/node_modules/request/main.js:119:22)
    at Request.<anonymous> (native)
```

**Comment by sergeche** [comment]
Наверно, немного поменялся формат документации. Посмотрю на досуге, что тут может быть

**Comment by macik** [comment]
Люди добрые, может кто сгенерил файлы для jQuery 1.7.х ? Поделитесь...

[Сам под Win7 сижу и *nix под рукой нет, даже Нод установил для такого случая, но запустить генератор не получилось, библиотека libxmljs автоматом ставиться под виндовый Нод не хочет, требует каких-то сугубо юниксовых утилит для настройки.]

**Comment by ogonkov** [comment]
Пока что парсер с новой версией документации не дружит, как я понял.
